# Generated by Django 5.0.6 on 2024-07-19 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_agregarproductos_nombre_alter_agregarproductos_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('direccion', models.CharField(max_length=20)),
                ('comuna', models.IntegerField(choices=[(0, 'Santiago'), (1, 'Cerrillos'), (2, 'Cerro Navia'), (3, 'Conchalí'), (4, 'El Bosque'), (5, 'Estación Central'), (6, 'Huechuraba'), (7, 'Independencia'), (8, 'La Cisterna'), (9, 'La Florida'), (10, 'La Granja'), (11, 'La Pintana'), (12, 'La Reina'), (13, 'Las Condes'), (14, 'Lo Barnechea'), (15, 'Lo Espejo'), (16, 'Lo Prado'), (17, 'Macul'), (18, 'Maipú'), (19, 'Ñuñoa'), (20, 'Providencia'), (21, 'Quilicura'), (22, 'Quinta Normal'), (23, 'Recoleta'), (24, 'Renca'), (25, 'San Joaquín'), (26, 'San Miguel'), (27, 'San Ramón'), (28, 'Vitacura')])),
            ],
        ),
        migrations.DeleteModel(
            name='Envios',
        ),
        migrations.AlterField(
            model_name='agregarproductos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='files/'),
        ),
    ]
